table _Measures
	lineageTag: 76fd4f88-31c5-49e9-a120-b1b87653b180

	measure 'Attrition Rate' = DIVIDE([Total Attrition], [Total Employees], 0)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Key Counts
		lineageTag: 1dbf3586-7b12-4804-b693-b7031f1c29a6

	measure 'Avg Age' = AVERAGE('HR Analytics'[Age])
		displayFolder: Key Averages
		lineageTag: a7952b76-0ee6-4f62-8aba-5c0a3b41e3fe

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Environment Satisfaction' = AVERAGE('HR Analytics'[Environment Satisfaction])
		displayFolder: Key Averages
		lineageTag: f357d03c-fa73-49b2-a8f9-e2a1d7b9adfc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Job Satisfaction' = AVERAGE('HR Analytics'[Job Satisfaction])
		displayFolder: Key Averages
		lineageTag: 29149396-bf36-4204-ae6c-3b2dd8abf79a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Job Satisfaction Leavers' = CALCULATE([Avg Job Satisfaction], 'HR Analytics'[Attrition Status] = "Left")
		displayFolder: For Tooltips
		lineageTag: 08d5572f-74cf-4dae-a92e-25790fc08ae1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Monthly Income' = AVERAGE('HR Analytics'[Monthly Income])
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: Key Averages
		lineageTag: c774ceaf-2fd1-45d8-8398-7c26fd9ffd44

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Avg Monthly Income Leavers' = CALCULATE([Avg Monthly Income], 'HR Analytics'[Attrition Status] = "Left")
		displayFolder: For Tooltips
		lineageTag: c017c8c5-ae5f-4820-b9c7-742b02a7c158

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Percent Salary Hike' = AVERAGE('HR Analytics'[Percent Salary Hike])
		formatString: 0.0
		displayFolder: Key Averages
		lineageTag: 3b3e2a97-53b6-4d8f-9d26-f14e94cf466a

	measure 'Avg Performance Rating' = AVERAGE('HR Analytics'[Performance Rating])
		displayFolder: Key Averages
		lineageTag: 6d513f44-68f0-4cf1-b91f-2d3569200959

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Work Life Balance' = AVERAGE('HR Analytics'[Work Life Balance])
		displayFolder: Key Averages
		lineageTag: 4c806dd9-9f6b-4514-a53c-b9e44e49be8a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Years At Company' = AVERAGE('HR Analytics'[Years At Company])
		displayFolder: Key Averages
		lineageTag: e18fb869-c095-420a-a8f3-9448478c89c0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Years At Company Leavers' = CALCULATE([Avg Years At Company], 'HR Analytics'[Attrition Status] = "Left")
		displayFolder: For Tooltips
		lineageTag: 31291d80-7fd4-4d23-987b-acc76d1ed7d6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Overtime Rate' = DIVIDE([Total Overtime Employees], [Total Employees], 0)
		displayFolder: Key Counts
		lineageTag: 2367d036-c00f-478a-a739-85b61e3c0728

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Attrition' = CALCULATE([Total Employees], 'HR Analytics'[Attrition Status] = "Left")
		formatString: 0
		displayFolder: Key Counts
		lineageTag: ada951fd-9e6b-431d-823b-58eeef756e14

	measure 'Total Employees' = COUNTROWS('HR Analytics')
		formatString: 0
		displayFolder: Key Counts
		lineageTag: eea6e9f1-f92e-4d68-b8ca-91daef664e00

	measure 'Total Overtime Employees' = CALCULATE([Total Employees], 'HR Analytics'[Over Time Status] = "Works Overtime")
		formatString: 0
		displayFolder: Key Counts
		lineageTag: e3da6c31-2f3b-4a08-9b86-1857f91955aa

	partition _Measures = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

